#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# scripts/circleci_env_bootstrap.sh
# ─────────────────────────────────────────────────────────────────────────────
# Materialise a runtime .env from CircleCI Context environment variables.
#
# This is the env-transfer required by the user: every variable listed in
# configs/env_template.sh has a matching entry in the `torshield-ir-secrets`
# CircleCI Context (Project Settings → Contexts). At job start, CircleCI
# exposes those Context vars as plain shell env vars; this script picks
# them up and writes a properly-formatted .env file so that every Python
# module which calls `load_dotenv()` continues to work unchanged.
#
# Variables NOT set in the Context are written as empty assignments so the
# file matches the template's shape — no KeyError downstream.
#
# SAFETY:
#   - The script NEVER prints secret values to stdout (only names).
#   - The .env file is chmod 600 and never persisted as an artifact
#     (see .gitignore + .circleci/config.yml store_artifacts excludes).
#   - CircleCI's mask feature will redact any secret that accidentally
#     leaks in `set -x` output.
# ════════════════════════════════════════════════════════════════════════════
set -euo pipefail

ENV_FILE="${1:-.env}"
TEMPLATE="${2:-configs/env_template.sh}"

if [ ! -f "$TEMPLATE" ]; then
    echo "FATAL: template $TEMPLATE not found" >&2
    exit 1
fi

echo "→ Materialising $ENV_FILE from CircleCI Context variables..."

# Header — preserves the project's branding for downstream tooling that greps it.
cat > "$ENV_FILE" <<'HEADER'
# ════════════════════════════════════════════════════════════════════════════
# AUTO-GENERATED by scripts/circleci_env_bootstrap.sh
# Source: CircleCI Context `torshield-ir-secrets`
# DO NOT EDIT BY HAND — edit the Context instead:
#   https://app.circleci.com/settings/organization/<org>/contexts
# ════════════════════════════════════════════════════════════════════════════
HEADER

# Walk the template; for each KEY= line, emit KEY=${KEY:-} so the value
# comes from the live environment (set by the Context) and falls back to
# empty string if unset.
written=0
skipped=0
while IFS= read -r line; do
    # Strip leading comment marker so we still pick up commented-out KEY= lines
    # in the template — the template marks optional vars with comments.
    stripped="${line#\#}"
    stripped="${stripped## }"  # left-trim
    case "$stripped" in
        *=*)
            key="${stripped%%=*}"
            # Validate the key looks like an env var name.
            if [[ ! "$key" =~ ^[A-Z][A-Z0-9_]+$ ]]; then
                continue
            fi
            # Skip empty/quoted default values from the template; we only
            # care about the key name.
            val="${!key:-}"
            printf '%s=%s\n' "$key" "$val" >> "$ENV_FILE"
            if [ -n "$val" ]; then
                written=$((written + 1))
            else
                skipped=$((skipped + 1))
            fi
            ;;
    esac
done < "$TEMPLATE"

# Append the runtime-only vars that are NOT in the template but are required
# by the scheduled-pipeline jobs.
cat >> "$ENV_FILE" <<'RUNTIME'

# ─────────────────────────────────────────────────────────────────────────────
# CircleCI runtime (auto-populated, do not override in Context)
# ─────────────────────────────────────────────────────────────────────────────
CI=true
CI_PROVIDER=circleci
CIRCLE_BUILD_URL="${CIRCLE_BUILD_URL:-}"
CIRCLE_PROJECT_REPONAME="${CIRCLE_PROJECT_REPONAME:-}"
CIRCLE_BRANCH="${CIRCLE_BRANCH:-main}"
CIRCLE_SHA1="${CIRCLE_SHA1:-}"
RUNTIME

chmod 600 "$ENV_FILE"

echo "✓ Wrote $ENV_FILE"
echo "  Entries with values : $written"
echo "  Entries empty       : $skipped  (set them in the Context if needed)"

# Audit list — print names of empty vars so the user knows what to set.
echo
echo "→ Empty vars (need Context entries if used by this job):"
while IFS= read -r line; do
    case "$line" in
        *=*)
            key="${line%%=*}"
            val="${line#*=}"
            if [ -z "$val" ] && [ "$key" != "CI" ] && [ "$key" != "CI_PROVIDER" ]; then
                echo "    - $key"
            fi
            ;;
    esac
done < "$ENV_FILE" | sort -u | head -50
